---
title: Sistema de Educación Remota
baseURL: "/"
params:
  palette: blue
  header:
    title: Tecnologías México
    logo_img: "/images/tmx-1.jpg"
    has_nav: true
    menu:
      actions:
      - label: Empezar
        url: "/signup"
  footer:
    logo_img: "/images/tmx-2.jpg"
    tagline: SaaS theme by Stackbit
    has_nav: true
    nav_title: Empresa
    has_social: true
    social_title: Comunidad
    has_subscribe: true
    subscribe_title: Subscribe
    subscribe_content: Mantente actualizado con las últimas noticias
    content: "&copy; UnoZero Code. All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
